### ISSUE TITLE
Fix deprecation warnings under Elixir 1.15

### ISSUE THREAD

**Issue by rob-vetspire** [Vetspire/sibyl#33]
Fix deprecation warnings under Elixir 1.15. The deprecation warnings are:

```elixir
==> sibyl
Compiling 13 files (.ex)
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
  (sibyl 0.1.8) lib/sibyl/handlers.ex:57: Sibyl.Handlers.ensure_name/1

warning: :dbg.stop_clear/0 is deprecated. It will be removed in OTP 27. Use dbg:stop/0 instead
Invalid call found at 2 locations:
  (sibyl 0.1.8) lib/sibyl/dynamic.ex:33: Sibyl.Dynamic.enable/1
  (sibyl 0.1.8) lib/sibyl/dynamic.ex:49: Sibyl.Dynamic.disable/0

warning: Exception.exception?/1 is deprecated. Use Kernel.is_exception/1 instead
  (sibyl 0.1.8) lib/sibyl/handlers/open_telemetry.ex:134: Sibyl.Handlers.OpenTelemetry.do_handle_event/4
```

**Comment by vereis** [comment]
Resolved in #34
